### ISSUE TITLE
학교 검색 API

### ISSUE THREAD

**Issue by gimhanul** [Bamdoliro/marubase#10]
### ✨ Describe

학교 검색 API를 제공해야 합니다.

### ✅ Tasks

- [x] feign client setting
- [x] neis api setting
- [x] search school api
