### ISSUE TITLE
각종 세팅

### ISSUE THREAD

**Issue by gimhanul** [Bamdoliro/marubase#3]
### ✨ Describe

각종 세팅을 해야 합니다.

### ✅ Tasks

- [x] rest docs 각종 base entity 추가
- [x] base entity 추가 (createdAt, updatedAt)
- [x] rest docs error code 추가
- [x] rest docs 개요 페이지 추가
- [x] cors 세팅
- [x] CI 세팅

### 🙋🏻 More

개요 페이지에 서버 로컬, 개발, 프로덕션 서버 주소 적기
